name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter


dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  hex: ^0.2.0
  http: ^0.13.6
  pointycastle: ^3.7.3
  riverpod: ^2.3.6
  ethers: ^0.0.1+3
  openpgp: ^3.5.4
  web3dart: ^2.6.1
  eth_sig_util: ^0.0.9
  encrypt: ^5.0.1
  cryptography: ^2.5.0


  push_api_dart:
    path: '../'
